# SPDX-License-Identifier: GPL-2.0-or-later

obj-m += surface_sam_ssh.o
obj-m += clients/

#ccflags-y += -DDEBUG
#ccflags-y += -DCONFIG_SURFACE_SAM_SSH_ERROR_INJECTION
ccflags-y += -Wall -Wextra
ccflags-y += -Wno-unused-parameter -Wno-missing-field-initializers
ccflags-y += -Wmaybe-uninitialized -Wuninitialized
ccflags-y += -I$(src) -I$(src)/include
