# SPDX-License-Identifier: GPL-2.0-or-later

obj-m += surface_sam_ssh.o
obj-m += surface_sam_san.o
obj-m += surface_sam_dtx.o
obj-m += surface_sam_hps.o
obj-m += surface_sam_vhf.o
obj-m += surface_sam_sid.o
obj-m += surface_sam_sid_gpelid.o
obj-m += surface_sam_sid_perfmode.o
obj-m += surface_sam_sid_power.o
obj-m += surface_sam_sid_vhf.o

ccflags-y += -DCONFIG_SURFACE_SAM_SSH_DEBUG_DEVICE
ccflags-y += -Wall -Wextra
ccflags-y += -Wno-unused-parameter -Wno-missing-field-initializers
