# SPDX-License-Identifier: GPL-2.0+
# Copyright (C) 2019-2022 Maximilian Luz <luzmaximilian@gmail.com>

obj-m += surface_acpi_notify.o
obj-m += surface_aggregator_cdev.o
obj-m += surface_aggregator_hub.o
obj-m += surface_aggregator_registry.o
obj-m += surface_aggregator_tabletsw.o
obj-m += surface_battery.o
obj-m += surface_charger.o
obj-m += surface_dtx.o
obj-m += surface_hid_core.o
obj-m += surface_hid.o
obj-m += surface_kbd.o
obj-m += surface_platform_profile.o
obj-m += surface_temp.o

#ccflags-y += -DDEBUG
ccflags-y += -Wall -Wextra
ccflags-y += -Wno-unused-parameter -Wno-missing-field-initializers -Wno-type-limits
ccflags-y += -Wmaybe-uninitialized -Wuninitialized
