# SPDX-License-Identifier: GPL-2.0-or-later

obj-m += surface_sam_san.o
obj-m += surface_sam_dtx.o
obj-m += surface_sam_hps.o
obj-m += surface_sam_vhf.o
obj-m += surface_sam_device_hub.o
obj-m += surface_sam_sid_perfmode.o
obj-m += surface_sam_sid_power.o
obj-m += surface_sam_sid_vhf.o
obj-m += surface_sam_debugfs.o

#ccflags-y += -DDEBUG
ccflags-y += -Wall -Wextra
ccflags-y += -Wno-unused-parameter -Wno-missing-field-initializers
ccflags-y += -Wmaybe-uninitialized -Wuninitialized
ccflags-y += -I$(src)/../../include

# switch to handle support for both patched and non-patched kernels
ccflags-$(__KERNEL_HAS_SSAM_MODALIAS_SUPPORT__) += -D__KERNEL_HAS_SSAM_MODALIAS_SUPPORT__=1
